#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &
dunst &

nvidia-settings --load-config-only

xsetroot -cursor_name left_ptr

bspc monitor DP-4 -d I II III IV V
bspc monitor HDMI-0 -d VI VII IIX IX X
bspc monitor DP-4 -s HDMI-0

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.7
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config border_radius 18
bspc config focus_follows_pointer true
 
bspc rule -a discord desktop='^4'
bspc rule -a Org.gnome.Nautilus state=floating follow=on focus=on

wmname LG3

~/.bin/wallpaper/change_wallpaper.sh &
~/.bin/spotify/launchlistener.sh &
~/.bin/floating.sh &

~/.config/polybar/material/launch.sh &

discord &
